# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6975ef450a3bf6b7857e1617f15bfb3798b94abbcc720f6d474e47538ef2b0b1d928e67298c8c876a76502b6e5e7479176cd1d1697e9c03645f0b997feee11b

test:
  secret_key_base: e2026bf6d57bb909e84430b9b3669c7dff7a0ca6a1aa87df914a04d010e75028217b256e4a63fdce286d48272b30c522130eb21eaa84613c5e1b601b5bb9b43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
